export const CREATE_FEED_ITEM = 'CREATE_FEED_ITEM';
export const CREATE_FEED_ITEM_SUCCESS = 'CREATE_FEED_ITEM_SUCCESS';
export const CREATE_FEED_ITEM_ERROR = 'CREATE_FEED_ITEM_ERROR';

export const UPDATE_FEED_ITEM = 'UPDATE_FEED_ITEM';
export const UPDATE_FEED_ITEM_SUCCESS = 'UPDATE_FEED_ITEM_SUCCESS';
export const UPDATE_FEED_ITEM_ERROR = 'UPDATE_FEED_ITEM_ERROR';

export const DELETE_FEED_ITEM = 'DELETE_FEED_ITEM';
export const DELETE_FEED_ITEM_SUCCESS = 'DELETE_FEED_ITEM_SUCCESS';
export const DELETE_FEED_ITEM_ERROR = 'DELETE_FEED_ITEM_ERROR';

export const REQUEST_FEED = 'REQUEST_FEED';
export const REQUEST_FEED_SUCCESS = 'REQUEST_FEED_SUCCESS';
export const REQUEST_FEED_ERROR = 'REQUEST_FEED_ERROR';
