export const ADD_FEED_ITEM = 'ADD_FEED_ITEM';
export const REMOVE_FEED_ITEM = 'REMOVE_FEED_ITEM';
export const UPDATE_FEED_ITEM = 'UPDATE_FEED_ITEM';
export const REQUEST_FEED = 'REQUEST_FEED';
export const REQUEST_FEED_SUCCESS = 'REQUEST_FEED_SUCCESS';
export const REQUEST_FEED_ERROR = 'REQUEST_FEED_ERROR';
